apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: cors
  namespace: ingress-gw
spec:
  options:
    cors:
      allowOrigin:
        - "*"
      allowHeaders:
        - "Content-Type"
        - "Authorization"
        - "Access-Control-Allow-Origin"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true